// jtwwfwfest_game_sdram.v is automatically generated by JTFRAME
// Do not modify it
// Do not add it to git

`ifndef JTFRAME_COLORW
`define JTFRAME_COLORW 4
`endif

`ifndef JTFRAME_BUTTONS
`define JTFRAME_BUTTONS 2
`endif

module jtwwfwfest_game_sdram(
    `include "jtframe_common_ports.inc"
    `include "jtframe_mem_ports.inc"
);

/* verilator lint_off WIDTH */
localparam [25:0] BA1_START  =`ifdef JTFRAME_BA1_START  `JTFRAME_BA1_START  `else 26'd0 `endif;
localparam [25:0] BA2_START  =`ifdef JTFRAME_BA2_START  `JTFRAME_BA2_START  `else 26'd0 `endif;
localparam [25:0] BA3_START  =`ifdef JTFRAME_BA3_START  `JTFRAME_BA3_START  `else 26'd0 `endif;
localparam [25:0] PROM_START =`ifdef JTFRAME_PROM_START `JTFRAME_PROM_START `else 26'd0 `endif;
localparam [25:0] HEADER_LEN =`ifdef JTFRAME_HEADER     `JTFRAME_HEADER     `else 26'd0 `endif;
localparam        SDRAMW     =`ifdef JTFRAME_SDRAM_XL 25 `elsif JTFRAME_SDRAM_LARGE 24 `else 23 `endif;
localparam        IOCTL_AW   =`ifdef JTFRAME_SDRAM_XL 27 `else 26 `endif;
/* verilator lint_on WIDTH */


parameter RAM_OFFSET = 22'h3F_0000;
parameter PCM_OFFSET = (`PCM_START-`JTFRAME_BA1_START)>>1;
parameter SCR_OFFSET = (`SCR_START-`JTFRAME_BA2_START)>>1;

// Audio channels 
wire signed [13:0] pcm;
wire signed [15:0] fm_l, fm_r;
wire mute;
// Additional ports
wire [15:0] main_dout;
wire [10:1] fgcode_addr;
wire [11:1] txt_addr;
wire [15:0] txt_dout;
wire [11:1] main_txt_addr;
wire [15:0] main_palram_dout;
wire [1:0] txt_we;
wire [12:1] main_objram_addr;
wire [15:0] palram_dout;
wire [13:1] main_palram_addr;
wire [1:0] palram_we;
wire [10:1] fgattr_addr;
wire [10:1] main_fg_addr;
wire [1:0] bg_we;
wire [12:1] objram_addr;
wire [1:0] objram_we;
wire [15:0] main_txt_din;
wire [1:0] fgattr_we;
wire [1:0] fgcode_we;
wire [15:0] bg_dout;
wire [15:0] main_txt_dout;
wire [15:0] main_fgcode_dout;
wire [11:1] bg_addr;
wire [15:0] main_bg_dout;
wire [15:0] objram_dout;
wire [15:0] main_objram_dout;
wire [15:0] fgattr_dout;
wire [15:0] main_fgattr_dout;
wire [11:1] main_bg_addr;
wire [13:1] palram_addr;
wire [15:0] fgcode_dout;

// BRAM buses












// SDRAM buses

wire [13:1] ram_addr;
wire [15:0] ram_data;
wire        ram_cs, ram_ok;
wire        ram_we;
wire [15:0] ram_din;
wire [ 1:0] ram_dsn;

wire [18:1] main_addr;
wire [15:0] main_data;
wire        main_cs, main_ok;
wire [15:0] snd_addr;
wire [ 7:0] snd_data;
wire        snd_cs, snd_ok;
wire [18:0] pcm_addr;
wire [ 7:0] pcm_data;
wire        pcm_cs, pcm_ok;
wire [16:2] char_addr;
wire [31:0] char_data;
wire        char_cs, char_ok;
wire [18:2] fgrom_addr;
wire [31:0] fgrom_data;
wire        fgrom_cs, fgrom_ok;
wire [18:2] bgrom_addr;
wire [31:0] bgrom_data;
wire        bgrom_cs, bgrom_ok;
wire [22:2] obj_addr;
wire [31:0] obj_data;
wire        obj_cs, obj_ok;
wire        prom_we, header;
wire [SDRAMW-2:0] raw_addr, post_addr;
wire [SDRAMW-2:0] ioctl_prog_addr   = ioctl_addr[SDRAMW-2:0];
wire [IOCTL_AW-1:0] pre_addr, dwnld_addr, ioctl_addr_noheader;
wire [ 7:0] post_data;
wire [15:0] raw_data;
wire [ 7:0] pcb_id;
wire        pass_io;
// Clock enable signals
wire cen_fm; 
wire cen_fm2; 
wire cen_oki; 
wire gfx4_en, gfx8_en, gfx16_en, gfx16b_en, gfx16c_en, ioctl_dwn;

assign pass_io = header | ioctl_ram;
assign ioctl_addr_noheader = `ifdef JTFRAME_HEADER header ? ioctl_addr : ioctl_addr - HEADER_LEN `else ioctl_addr `endif ;
`ifdef JTFRAME_SDRAM_CACHE
assign burst_addr = { (SDRAMW-1){1'b0} };
assign burst_ba   = 2'd0;
assign burst_rd   = 1'b0;
assign burst_wr   = 1'b0;
assign burst_din  = 16'd0;
`endif

wire rst_h, rst24_h, rst48_h, hold_rst;

/* verilator tracing_off */
jtframe_rsthold u_hold(
    .rst    ( rst       ),
    .clk    ( clk       ),
    .hold   ( hold_rst  ),
    .rst_h  ( rst_h     ),
    .rst24  ( rst24     ),
    .clk24  ( clk24     ),
    .rst24_h( rst24_h   )
`ifdef JTFRAME_CLK48 ,
    .rst48  ( rst48     ),
    .clk48  ( clk48     ),
    .rst48_h( rst48_h   )
`endif
);
/* verilator tracing_on */
jtwwfwfest_game u_game(
    .rst        ( rst_h     ),
    .clk        ( clk       ),
    .rst24      ( rst24_h   ),
    .clk24      ( clk24     ),
`ifdef JTFRAME_CLK48
    .rst48      ( rst48_h   ),
    .clk48      ( clk48     ),
`endif
    .rst96      ( rst96     ),
    .clk96      ( clk96     ),
    // Audio channels
    .pcm     ( pcm      ),.fm_l   ( fm_l    ),
    .fm_r   ( fm_r    ),
    
    .snd_en         ( snd_en        ),
    .snd_vol        ( snd_vol       ),
    .cen_fm    ( cen_fm    ), 
    .cen_fm2    ( cen_fm2    ), 
    .cen_oki    ( cen_oki    ), 

    .pxl2_cen       ( pxl2_cen      ),
    .pxl_cen        ( pxl_cen       ),
    .red            ( red           ),
    .green          ( green         ),
    .blue           ( blue          ),
    .LHBL           ( LHBL          ),
    .LVBL           ( LVBL          ),
    .HS             ( HS            ),
    .VS             ( VS            ),
    // cabinet I/O
    .cab_1p   ( cab_1p  ),
    .coin     ( coin    ),
    .joystick1    ( joystick1        ), .joystick2    ( joystick2        ),
    .joystick3    ( joystick3        ), .joystick4    ( joystick4        ), `ifdef JTFRAME_MOUSE
    .mouse_1p     ( mouse_1p         ), .mouse_2p     ( mouse_2p         ), .mouse_strobe ( mouse_strobe ), `endif `ifdef JTFRAME_LIGHTGUN
    .gun_1p_x     ( gun_1p_x         ), .gun_1p_y     ( gun_1p_y         ),
    .gun_2p_x     ( gun_2p_x         ), .gun_2p_y     ( gun_2p_y         ), `endif `ifdef JTFRAME_SPINNER
    .spinner_1p   ( spinner_1p       ), .spinner_2p   ( spinner_2p       ), `endif
    .joyana_l1    ( joyana_l1        ), .joyana_l2    ( joyana_l2        ),
    .joyana_l3    ( joyana_l3        ), .joyana_l4    ( joyana_l4        ),
    .joyana_r1    ( joyana_r1        ), .joyana_r2    ( joyana_r2        ),
    .joyana_r3    ( joyana_r3        ), .joyana_r4    ( joyana_r4        ),
    .dial_x       ( dial_x           ), .dial_y       ( dial_y           ),
    // DIP switches
    .status         ( status        ),
    .dipsw          ( dipsw         ),
    .service        ( service       ),
    .tilt           ( tilt          ),
    .dip_pause      ( dip_pause     ),
    .dip_flip       ( dip_flip      ),
    .dip_test       ( dip_test      ),
    .dip_fxlevel    ( dip_fxlevel   ),
    // Ports declared in mem.yaml
    .main_dout   ( main_dout ),
    .fgcode_addr   ( fgcode_addr ),
    .txt_addr   ( txt_addr ),
    .txt_dout   ( txt_dout ),
    .main_txt_addr   ( main_txt_addr ),
    .main_palram_dout   ( main_palram_dout ),
    .txt_we   ( txt_we ),
    .main_objram_addr   ( main_objram_addr ),
    .palram_dout   ( palram_dout ),
    .main_palram_addr   ( main_palram_addr ),
    .palram_we   ( palram_we ),
    .fgattr_addr   ( fgattr_addr ),
    .main_fg_addr   ( main_fg_addr ),
    .bg_we   ( bg_we ),
    .objram_addr   ( objram_addr ),
    .objram_we   ( objram_we ),
    .main_txt_din   ( main_txt_din ),
    .fgattr_we   ( fgattr_we ),
    .fgcode_we   ( fgcode_we ),
    .bg_dout   ( bg_dout ),
    .main_txt_dout   ( main_txt_dout ),
    .main_fgcode_dout   ( main_fgcode_dout ),
    .bg_addr   ( bg_addr ),
    .main_bg_dout   ( main_bg_dout ),
    .objram_dout   ( objram_dout ),
    .main_objram_dout   ( main_objram_dout ),
    .fgattr_dout   ( fgattr_dout ),
    .main_fgattr_dout   ( main_fgattr_dout ),
    .main_bg_addr   ( main_bg_addr ),
    .palram_addr   ( palram_addr ),
    .fgcode_dout   ( fgcode_dout ),
    // Memory interface - SDRAM
    .ram_addr ( ram_addr ),
    .ram_cs   ( ram_cs   ),
    .ram_ok   ( ram_ok   ),
    .ram_data ( ram_data ),
    .ram_we   ( ram_we   ),
    .ram_dsn  ( ram_dsn  ),
    
    
    .main_addr ( main_addr ),
    .main_cs   ( main_cs   ),
    .main_ok   ( main_ok   ),
    .main_data ( main_data ),
    
    .snd_addr ( snd_addr ),
    .snd_cs   ( snd_cs   ),
    .snd_ok   ( snd_ok   ),
    .snd_data ( snd_data ),
    
    .pcm_addr ( pcm_addr ),
    .pcm_cs   ( pcm_cs   ),
    .pcm_ok   ( pcm_ok   ),
    .pcm_data ( pcm_data ),
    
    .char_addr ( char_addr ),
    .char_cs   ( char_cs   ),
    .char_ok   ( char_ok   ),
    .char_data ( char_data ),
    
    .fgrom_addr ( fgrom_addr ),
    .fgrom_cs   ( fgrom_cs   ),
    .fgrom_ok   ( fgrom_ok   ),
    .fgrom_data ( fgrom_data ),
    
    .bgrom_addr ( bgrom_addr ),
    .bgrom_cs   ( bgrom_cs   ),
    .bgrom_ok   ( bgrom_ok   ),
    .bgrom_data ( bgrom_data ),
    
    .obj_addr ( obj_addr ),
    .obj_cs   ( obj_cs   ),
    .obj_ok   ( obj_ok   ),
    .obj_data ( obj_data ),
    
    // Memory interface - BRAM

    
    
    
    
    
    
    
    
    
    
    
    
`ifdef JTFRAME_SRAM
    // SRAM
    .sram_addr  ( sram_addr     ),
    .sram_din   ( sram_din      ),
    .sram_dout  ( sram_dout     ),
    .sram_wen   ( sram_wen      ),
    .sram_dsn   ( sram_dsn      ),
    .sram_ok    ( sram_ok       ),
`endif

`ifdef JTFRAME_SAVEGAME
    // Save/Load
    .sav_change ( sav_change    ),
    .sav_wait   ( sav_wait      ),
    .sav_done   ( sav_done      ),
    .sav_wr     ( sav_wr        ),
    .sav_ack    ( sav_ack       ),
    .sav_din    ( sav_din       ),
    .sav_dout   ( sav_dout      ),
    .sav_addr   ( sav_addr      ),
`endif
    // PROM writting
    .ioctl_addr   ( pass_io ? ioctl_addr       : ioctl_addr_noheader  ),
    .prog_addr    ( pass_io ? ioctl_prog_addr : raw_addr      ),
    .prog_data    ( pass_io ? ioctl_dout       : raw_data[7:0] ),
    .prog_we      ( pass_io ? ioctl_wr         : prog_we       ),
    .prog_ba      ( prog_ba        ), // prog_ba supplied in case it helps re-mapping addresses
    .prom_we      ( pass_io ? 1'b0 : prom_we ),
`ifdef JTFRAME_HEADER
    .header       ( header         ),
`endif
`ifdef JTFRAME_IOCTL_RD
    .ioctl_din    ( ioctl_din      ),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ), `endif
    .ioctl_ram    ( ioctl_ram      ),
    .ioctl_cart   ( ioctl_cart     ),
    // Debug
    .debug_bus    ( debug_bus      ),
    .debug_view   ( debug_view     ),
`ifdef JTFRAME_STATUS
    .st_addr      ( st_addr        ),
    .st_dout      ( st_dout        ),
`endif
`ifdef JTFRAME_LF_BUFFER
    .game_vrender( game_vrender  ),
    .game_hdump  ( game_hdump    ),
    .ln_addr     ( ln_addr       ),
    .ln_data     ( ln_data       ),
    .ln_done     ( ln_done       ),
    .ln_hs       ( ln_hs         ),
    .ln_dout     ( ln_dout       ),
    .ln_pxl      ( ln_pxl        ),
    .ln_v        ( ln_v          ),
    .ln_vs       ( ln_vs         ),
    .ln_lvbl     ( ln_lvbl       ),
    .ln_we       ( ln_we         ),
    .fb_keep     ( fb_keep       ),
`ifdef JTFRAME_LF_ZOOM
    .h_step      ( h_step        ),
    .v_step      ( v_step        ),
`endif
`endif
    .gfx_en      ( gfx_en        )
);
/* verilator tracing_off */
assign dwnld_busy = ioctl_rom | prom_we | prog_we; // prom_we is really just for sims
assign dwnld_addr = ioctl_addr;
`ifdef JTFRAME_SDRAM_XL
wire [26:0] dwnld_addr_wide = dwnld_addr;
`else
wire [26:0] dwnld_addr_wide = {1'b0,dwnld_addr};
`endif
assign prog_addr = raw_addr;
assign prog_data = raw_data;
assign gfx4_en   = 0;
assign gfx8_en   = (ioctl_addr>=((`JTFRAME_BA2_START)) && ioctl_addr<(`JTFRAME_BA2_START+(SCR_OFFSET<<1))) /* char */;
assign gfx16_en  = 0;
assign gfx16b_en = 0;
assign gfx16c_en = 0;
assign ioctl_dwn = ioctl_rom | ioctl_cart;
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_dwnld #(
    .SDRAMW     ( SDRAMW       ),
`ifdef JTFRAME_HEADER
    .HEADER    ( `JTFRAME_HEADER   ),
`endif
`ifdef JTFRAME_BA1_START
    .BA1_START ( BA1_START ),
`endif
`ifdef JTFRAME_BA2_START
    .BA2_START ( BA2_START ),
`endif
`ifdef JTFRAME_BA3_START
    .BA3_START ( BA3_START ),
`endif
`ifdef JTFRAME_PROM_START
    .PROM_START( PROM_START ),
`endif
    .SWAB      ( 1),
    .GFX8B0    ( 0),
    .GFX16B0   ( 0)
) u_dwnld(
    .clk          ( clk            ),
    .ioctl_rom    ( ioctl_dwn      ),
    .ioctl_addr   ( dwnld_addr_wide),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .gfx4_en      ( gfx4_en        ),
    .gfx8_en      ( gfx8_en        ),
    .gfx16_en     ( gfx16_en       ),
    .gfx16b_en    ( gfx16b_en      ),
    .gfx16c_en    ( gfx16c_en      ),
    .prog_addr    ( raw_addr       ),
    .prog_data    ( raw_data       ),
    .prog_mask    ( prog_mask      ), // active low
    .prog_we      ( prog_we        ),
    .prog_rd      ( prog_rd        ),
    .prog_ba      ( prog_ba        ),
    .prom_we      ( prom_we        ),
    .header       ( header         ),
    .sdram_ack    ( prog_ack       )
);

jtframe_headerbyte #(.AW(6)) u_pcbid(
    .clk          ( clk            ),
    .header       ( header         ),
    .ioctl_addr   ( ioctl_addr[5:0]),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .dout         ( pcb_id         )
);
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif


jtframe_ram1_2slots #(
    .SDRAMW(SDRAMW-1),
    // ram
    .SLOT0_AW(13),
    .SLOT0_DW(16), 
    // main
    .SLOT1_AW(18),
    .SLOT1_DW(16)
`ifdef JTFRAME_BA0_LEN
    ,.SLOT1_DOUBLE(1)
`endif
) u_bank0(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( ram_addr  ),
    .hold_rst    (  hold_rst  ),
    .slot0_wen   ( ram_we    ),
    .slot0_din   ( main_dout   ),
    .slot0_wrmask( ram_dsn   ),
    .slot0_offset( RAM_OFFSET[SDRAMW-2:0] ),
    .slot0_dout  ( ram_data  ),
    .slot0_cs    ( ram_cs    ),
    .slot0_ok    ( ram_ok    ),
    
    .slot1_addr  ( main_addr  ),
    .slot1_clr   ( 1'b0       ), // only 1'b0 supported in mem.yaml
    .slot1_dout  ( main_data  ),
    .slot1_cs    ( main_cs    ),
    .slot1_ok    ( main_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[0]  ),
    .sdram_rd    ( ba_rd[0]   ),
    .sdram_addr  ( ba0_addr   ),
    .sdram_wr    ( ba_wr[0]   ),
    .sdram_wrmask( ba0_dsn    ),
    .data_write  ( ba0_din    ),
    .data_dst    ( ba_dst[0]  ),
    .data_rdy    ( ba_rdy[0]  ),
    .data_read   ( data_read  )
);
jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    // snd
    .SLOT0_AW(16),
    .SLOT0_DW( 8), 
    // pcm
    .SLOT1_OFFSET(PCM_OFFSET[SDRAMW-2:0]),
    .SLOT1_AW(19),
    .SLOT1_DW( 8)
`ifdef JTFRAME_BA1_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
) u_bank1(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( snd_addr  ),
    .slot0_dout  ( snd_data  ),
    .slot0_cs    ( snd_cs    ),
    .slot0_ok    ( snd_ok    ),
    
    .slot1_addr  ( pcm_addr  ),
    .slot1_dout  ( pcm_data  ),
    .slot1_cs    ( pcm_cs    ),
    .slot1_ok    ( pcm_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[1]  ),
    .sdram_rd    ( ba_rd[1]   ),
    .sdram_addr  ( ba1_addr   ),
    .data_dst    ( ba_dst[1]  ),
    .data_rdy    ( ba_rdy[1]  ),
    .data_read   ( data_read  )
);
assign ba_wr[1] = 0;
assign ba1_din  = 0;
assign ba1_dsn  = 3;
jtframe_rom_3slots #(
    .SDRAMW(SDRAMW-1),
    // char
    .SLOT0_AW(16),
    .SLOT0_DW(32), 
    // fgrom
    .SLOT1_OFFSET(SCR_OFFSET[SDRAMW-2:0]),
    .SLOT1_AW(18),
    .SLOT1_DW(32), 
    // bgrom
    .SLOT2_OFFSET(SCR_OFFSET[SDRAMW-2:0]),
    .SLOT2_AW(18),
    .SLOT2_DW(32)
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
    ,.SLOT2_DOUBLE(1)
`endif
) u_bank2(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { char_addr, 1'b0 } ),
    .slot0_dout  ( char_data  ),
    .slot0_cs    ( char_cs    ),
    .slot0_ok    ( char_ok    ),
    
    .slot1_addr  ( { fgrom_addr, 1'b0 } ),
    .slot1_dout  ( fgrom_data  ),
    .slot1_cs    ( fgrom_cs    ),
    .slot1_ok    ( fgrom_ok    ),
    
    .slot2_addr  ( { bgrom_addr, 1'b0 } ),
    .slot2_dout  ( bgrom_data  ),
    .slot2_cs    ( bgrom_cs    ),
    .slot2_ok    ( bgrom_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[2]  ),
    .sdram_rd    ( ba_rd[2]   ),
    .sdram_addr  ( ba2_addr   ),
    .data_dst    ( ba_dst[2]  ),
    .data_rdy    ( ba_rdy[2]  ),
    .data_read   ( data_read  )
);
assign ba_wr[2] = 0;
assign ba2_din  = 0;
assign ba2_dsn  = 3;
jtframe_rom_1slot #(
    .SDRAMW(SDRAMW-1),
    // obj
    .SLOT0_AW(22),
    .SLOT0_DW(32)
`ifdef JTFRAME_BA3_LEN
    ,.SLOT0_DOUBLE(1)
`endif
) u_bank3(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { obj_addr, 1'b0 } ),
    .slot0_dout  ( obj_data  ),
    .slot0_cs    ( obj_cs    ),
    .slot0_ok    ( obj_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[3]  ),
    .sdram_rd    ( ba_rd[3]   ),
    .sdram_addr  ( ba3_addr   ),
    .data_dst    ( ba_dst[3]  ),
    .data_rdy    ( ba_rdy[3]  ),
    .data_read   ( data_read  )
);
assign ba_wr[3] = 0;
assign ba3_din  = 0;
assign ba3_dsn  = 3;

`ifdef JTFRAME_PROM_START
localparam JTFRAME_PROM_START=`JTFRAME_PROM_START;
`endif

// Dual port BRAM for fgattr and main
jtframe_dual_ram16 #(
    .AW(11-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(0)
) u_bram_fgattr(
    // Port 0 - fgattr
    .clk0   ( clk ),
    .addr0  ( fgattr_addr ),
    .data0  ( 16'h0 ),
    .we0    ( 2'd0 ),
    .q0     ( fgattr_dout ),
    // Port 1 - main
    .clk1   ( clk ),
    .data1  ( main_dout ),
    .addr1  ( main_fg_addr[10:1] ),
    .we1    ( fgattr_we  ),
    .q1     ( main_fgattr_dout )
);
// Dual port BRAM for fgcode and main
jtframe_dual_ram16 #(
    .AW(11-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(0)
) u_bram_fgcode(
    // Port 0 - fgcode
    .clk0   ( clk ),
    .addr0  ( fgcode_addr ),
    .data0  ( 16'h0 ),
    .we0    ( 2'd0 ),
    .q0     ( fgcode_dout ),
    // Port 1 - main
    .clk1   ( clk ),
    .data1  ( main_dout ),
    .addr1  ( main_fg_addr[10:1] ),
    .we1    ( fgcode_we  ),
    .q1     ( main_fgcode_dout )
);
// Dual port BRAM for bg and main
jtframe_dual_ram16 #(
    .AW(12-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(0)
) u_bram_bg(
    // Port 0 - bg
    .clk0   ( clk ),
    .addr0  ( bg_addr ),
    .data0  ( 16'h0 ),
    .we0    ( 2'd0 ),
    .q0     ( bg_dout ),
    // Port 1 - main
    .clk1   ( clk ),
    .data1  ( main_dout ),
    .addr1  ( main_bg_addr[11:1] ),
    .we1    ( bg_we  ),
    .q1     ( main_bg_dout )
);
// Dual port BRAM for txt and main
jtframe_dual_ram16 #(
    .AW(12-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(0)
) u_bram_txt(
    // Port 0 - txt
    .clk0   ( clk ),
    .addr0  ( txt_addr ),
    .data0  ( 16'h0 ),
    .we0    ( 2'd0 ),
    .q0     ( txt_dout ),
    // Port 1 - main
    .clk1   ( clk ),
    .data1  ( main_txt_din ),
    .addr1  ( main_txt_addr[11:1] ),
    .we1    ( txt_we  ),
    .q1     ( main_txt_dout )
);
// Dual port BRAM for objram and main
jtframe_dual_ram16 #(
    .AW(13-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(0)
) u_bram_objram(
    // Port 0 - objram
    .clk0   ( clk ),
    .addr0  ( objram_addr ),
    .data0  ( 16'h0 ),
    .we0    ( 2'd0 ),
    .q0     ( objram_dout ),
    // Port 1 - main
    .clk1   ( clk ),
    .data1  ( main_dout ),
    .addr1  ( main_objram_addr[12:1] ),
    .we1    ( objram_we  ),
    .q1     ( main_objram_dout )
);
// Dual port BRAM for palram and main
jtframe_dual_ram16 #(
    .AW(14-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(0)
) u_bram_palram(
    // Port 0 - palram
    .clk0   ( clk ),
    .addr0  ( palram_addr ),
    .data0  ( 16'h0 ),
    .we0    ( 2'd0 ),
    .q0     ( palram_dout ),
    // Port 1 - main
    .clk1   ( clk ),
    .data1  ( main_dout ),
    .addr1  ( main_palram_addr[13:1] ),
    .we1    ( palram_we  ),
    .q1     ( main_palram_dout )
);


// Clock enable generation
// 3579544 = 48000000*4808/64473 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(2),.NUM(4808),.DEN(64473),.MFREQ(48000)) u_cen0_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { cen_fm2, cen_fm } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 1056000 = 48000000*11/500 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(11),.DEN(500),.MFREQ(48000)) u_cen1_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { cen_oki } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

`ifndef NOSOUND
`ifdef VERILATOR_KEEP_AUDIO /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
assign mute=0;

jtframe_rcmix #(
    .W0(14),
    .W1(16),
    .FIR0("fir_192k_4k.hex"),
    .STEREO0( 0),
    .STEREO1( 1),
    .STEREO2( 0),
    .STEREO3( 0),
    .STEREO4( 0),
    .STEREO5( 0),
    .DCRM0  ( 0),
    .DCRM1  ( 0),
    .DCRM2  ( 0),
    .DCRM3  ( 0),
    .DCRM4  ( 0),
    .DCRM5  ( 0),
    .STEREO ( 0),
    // Fractional cen for 192kHz
    .FRACW( 9), .FRACN(1), .FRACM(250)
) u_rcmix(
`ifdef JTFRAME_CLK48
    .rst    ( rst48     ),
    .clk    ( clk48     ),
`else
    .rst    ( rst       ),
    .clk    ( clk       ),
`endif
    .mute   ( mute      ),
    .sample ( sample    ),
    .ch_en  ( snd_en    ),
    .gpole  ( 15'h3F66 ),  // 19894 Hz 
    .ch0    ( pcm ),
    .ch1    ( { fm_l,fm_r } ),
    .ch2    ( 16'd0 ),
    .ch3    ( 16'd0 ),
    .ch4    ( 16'd0 ),
    .ch5    ( 16'd0 ),
    .p0     ( 30'h00), // 0 Hz, 0 Hz 
    .p1     ( {15'h00,15'h3E12}), // 20404 Hz, 0 Hz 
    .p2     ( 30'h0), 
    .p3     ( 30'h0), 
    .p4     ( 30'h0), 
    .p5     ( 30'h0), 
    .g0     ( 8'h80 ), // 1.00  pcm
    .g1     ( 8'h20 ), // 0.25  fm
    .g2     ( 8'h00 ), // 0.00 
    .g3     ( 8'h00 ), // 0.00 
    .g4     ( 8'h00 ), // 0.00 
    .g5     ( 8'h00 ), // 0.00 
    .gain   ( snd_vol   ),
    .mixed  ( snd       ),
    .peak   ( snd_peak  ),
    .vu     ( snd_vu    )
);
`else
assign snd=0;
assign snd_vu   = 0;
assign snd_peak = 0;
wire ncs;
jtframe_frac_cen #(.WC(9)) u_cen192(
    .clk    ( clk       ),
    .n      ( 1 ),
    .m      ( 250 ),
    .cen    ( {  ncs,sample }  ), // sample is always 192 kHz
    .cenb   (                  )
);
`endif
endmodule
